name: Upload Screenshots to screenshotbot.io

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.2.1'

      - name: Run recordPaparazziDevDebug task
        run: ./gradlew androidApp:recordPaparazziDevDebug

      - name: Setup screenshotbot.io script
        run: |
          curl https://cdn.screenshotbot.io/recorder.sh | sh

      - name: Upload screenshots
        run: |
          git fetch origin develop
          ~/screenshotbot/recorder \
            --directory androidApp/src/test/snapshots/images/ \
            --channel geotrainer \
            --main-branch develop \
            --repo-url https://github.com/romans-boi/geoguessr-trainer.git
      
        env:
          SCREENSHOTBOT_API_KEY: ${{ secrets.SCREENSHOTBOT_API_KEY }}
          SCREENSHOTBOT_API_SECRET: ${{ secrets.SCREENSHOTBOT_API_SECRET }}
