name: Upload Screenshots to screenshotbot.io

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Upload
        run: |
          ~/screenshotbot/recorder --directory androidApp/src/test/snapshots/images/ --channel geotrainer --main-branch develop
        env:
          SCREENSHOTBOT_API_KEY: ${{ secrets.SCREENSHOTBOT_API_KEY }}
          SCREENSHOTBOT_API_SECRET: ${{ secrets.SCREENSHOTBOT_API_SECRET }}
